// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: planetmsg/users/v1/friend_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GroupName string `protobuf:"bytes,1,opt,name=groupName,proto3" json:"groupName,omitempty"`
}

func (x *GroupReq) Reset() {
	*x = GroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_users_v1_friend_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupReq) ProtoMessage() {}

func (x *GroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_users_v1_friend_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupReq.ProtoReflect.Descriptor instead.
func (*GroupReq) Descriptor() ([]byte, []int) {
	return file_planetmsg_users_v1_friend_service_proto_rawDescGZIP(), []int{0}
}

func (x *GroupReq) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type NickReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nickName,proto3" json:"nickName,omitempty"`
}

func (x *NickReq) Reset() {
	*x = NickReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_users_v1_friend_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NickReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NickReq) ProtoMessage() {}

func (x *NickReq) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_users_v1_friend_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NickReq.ProtoReflect.Descriptor instead.
func (*NickReq) Descriptor() ([]byte, []int) {
	return file_planetmsg_users_v1_friend_service_proto_rawDescGZIP(), []int{1}
}

func (x *NickReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

var File_planetmsg_users_v1_friend_service_proto protoreflect.FileDescriptor

var file_planetmsg_users_v1_friend_service_proto_rawDesc = []byte{
	0x0a, 0x27, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2f, 0x76, 0x31, 0x2f, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x6c, 0x61, 0x6e, 0x65,
	0x74, 0x6d, 0x73, 0x67, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1d, 0x70,
	0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x28, 0x0a, 0x08,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a, 0x09, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x67, 0x72, 0x6f,
	0x75, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x07, 0x4e, 0x69, 0x63, 0x6b, 0x52, 0x65,
	0x71, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x32, 0x9f, 0x01,
	0x0a, 0x0d, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x46, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1c, 0x2e, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x74, 0x6d, 0x73, 0x67, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x73, 0x67, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x53, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x55, 0x73, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d,
	0x73, 0x67, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x69, 0x63, 0x6b,
	0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x22, 0x00, 0x42,
	0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6e,
	0x69, 0x6d, 0x65, 0x50, 0x6c, 0x75, 0x73, 0x48, 0x75, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2f,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_planetmsg_users_v1_friend_service_proto_rawDescOnce sync.Once
	file_planetmsg_users_v1_friend_service_proto_rawDescData = file_planetmsg_users_v1_friend_service_proto_rawDesc
)

func file_planetmsg_users_v1_friend_service_proto_rawDescGZIP() []byte {
	file_planetmsg_users_v1_friend_service_proto_rawDescOnce.Do(func() {
		file_planetmsg_users_v1_friend_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_planetmsg_users_v1_friend_service_proto_rawDescData)
	})
	return file_planetmsg_users_v1_friend_service_proto_rawDescData
}

var file_planetmsg_users_v1_friend_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_planetmsg_users_v1_friend_service_proto_goTypes = []interface{}{
	(*GroupReq)(nil), // 0: planetmsg.users.v1.GroupReq
	(*NickReq)(nil),  // 1: planetmsg.users.v1.NickReq
	(*MsgRsp)(nil),   // 2: planetmsg.users.v1.MsgRsp
	(*User)(nil),     // 3: planetmsg.users.v1.User
}
var file_planetmsg_users_v1_friend_service_proto_depIdxs = []int32{
	0, // 0: planetmsg.users.v1.FriendService.AddGroup:input_type -> planetmsg.users.v1.GroupReq
	1, // 1: planetmsg.users.v1.FriendService.SearchUsers:input_type -> planetmsg.users.v1.NickReq
	2, // 2: planetmsg.users.v1.FriendService.AddGroup:output_type -> planetmsg.users.v1.MsgRsp
	3, // 3: planetmsg.users.v1.FriendService.SearchUsers:output_type -> planetmsg.users.v1.User
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_planetmsg_users_v1_friend_service_proto_init() }
func file_planetmsg_users_v1_friend_service_proto_init() {
	if File_planetmsg_users_v1_friend_service_proto != nil {
		return
	}
	file_planetmsg_users_v1_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_planetmsg_users_v1_friend_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_planetmsg_users_v1_friend_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NickReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_planetmsg_users_v1_friend_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_planetmsg_users_v1_friend_service_proto_goTypes,
		DependencyIndexes: file_planetmsg_users_v1_friend_service_proto_depIdxs,
		MessageInfos:      file_planetmsg_users_v1_friend_service_proto_msgTypes,
	}.Build()
	File_planetmsg_users_v1_friend_service_proto = out.File
	file_planetmsg_users_v1_friend_service_proto_rawDesc = nil
	file_planetmsg_users_v1_friend_service_proto_goTypes = nil
	file_planetmsg_users_v1_friend_service_proto_depIdxs = nil
}
