// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        (unknown)
// source: planetmsg/users/v1/sign_up_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *EmailReq) Reset() {
	*x = EmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_users_v1_sign_up_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailReq) ProtoMessage() {}

func (x *EmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_users_v1_sign_up_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailReq.ProtoReflect.Descriptor instead.
func (*EmailReq) Descriptor() ([]byte, []int) {
	return file_planetmsg_users_v1_sign_up_service_proto_rawDescGZIP(), []int{0}
}

func (x *EmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CheckEmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email     string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	VaildCode string `protobuf:"bytes,2,opt,name=vaildCode,proto3" json:"vaildCode,omitempty"`
}

func (x *CheckEmailReq) Reset() {
	*x = CheckEmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_users_v1_sign_up_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailReq) ProtoMessage() {}

func (x *CheckEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_users_v1_sign_up_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailReq.ProtoReflect.Descriptor instead.
func (*CheckEmailReq) Descriptor() ([]byte, []int) {
	return file_planetmsg_users_v1_sign_up_service_proto_rawDescGZIP(), []int{1}
}

func (x *CheckEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CheckEmailReq) GetVaildCode() string {
	if x != nil {
		return x.VaildCode
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginName string `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Pwd       string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_users_v1_sign_up_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_users_v1_sign_up_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_planetmsg_users_v1_sign_up_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginReq) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *LoginReq) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type TokenRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Atoken string `protobuf:"bytes,1,opt,name=Atoken,proto3" json:"Atoken,omitempty"`
	Rtoken string `protobuf:"bytes,2,opt,name=Rtoken,proto3" json:"Rtoken,omitempty"`
	Msg    string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TokenRsp) Reset() {
	*x = TokenRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_users_v1_sign_up_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRsp) ProtoMessage() {}

func (x *TokenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_users_v1_sign_up_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRsp.ProtoReflect.Descriptor instead.
func (*TokenRsp) Descriptor() ([]byte, []int) {
	return file_planetmsg_users_v1_sign_up_service_proto_rawDescGZIP(), []int{3}
}

func (x *TokenRsp) GetAtoken() string {
	if x != nil {
		return x.Atoken
	}
	return ""
}

func (x *TokenRsp) GetRtoken() string {
	if x != nil {
		return x.Rtoken
	}
	return ""
}

func (x *TokenRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_planetmsg_users_v1_sign_up_service_proto protoreflect.FileDescriptor

var file_planetmsg_users_v1_sign_up_service_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2f, 0x75, 0x73, 0x65, 0x72,
	0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x74, 0x6d, 0x73, 0x67, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1d,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a,
	0x08, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22,
	0x43, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x69, 0x6c, 0x64, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x69, 0x6c, 0x64,
	0x43, 0x6f, 0x64, 0x65, 0x22, 0x3a, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77, 0x64,
	0x22, 0x4c, 0x0a, 0x08, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x41, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xb8,
	0x02, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x41, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x18, 0x2e, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x1a, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73,
	0x67, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x4a, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x61,
	0x6c, 0x69, 0x64, 0x12, 0x1c, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x51, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x21, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x71, 0x1a, 0x1a, 0x2e, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x45, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x1c, 0x2e, 0x70, 0x6c,
	0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x70, 0x6c, 0x61, 0x6e,
	0x65, 0x74, 0x6d, 0x73, 0x67, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x22, 0x00, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x50, 0x6c, 0x75,
	0x73, 0x48, 0x75, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2f,
	0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_planetmsg_users_v1_sign_up_service_proto_rawDescOnce sync.Once
	file_planetmsg_users_v1_sign_up_service_proto_rawDescData = file_planetmsg_users_v1_sign_up_service_proto_rawDesc
)

func file_planetmsg_users_v1_sign_up_service_proto_rawDescGZIP() []byte {
	file_planetmsg_users_v1_sign_up_service_proto_rawDescOnce.Do(func() {
		file_planetmsg_users_v1_sign_up_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_planetmsg_users_v1_sign_up_service_proto_rawDescData)
	})
	return file_planetmsg_users_v1_sign_up_service_proto_rawDescData
}

var file_planetmsg_users_v1_sign_up_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_planetmsg_users_v1_sign_up_service_proto_goTypes = []interface{}{
	(*EmailReq)(nil),      // 0: planetmsg.users.v1.EmailReq
	(*CheckEmailReq)(nil), // 1: planetmsg.users.v1.CheckEmailReq
	(*LoginReq)(nil),      // 2: planetmsg.users.v1.LoginReq
	(*TokenRsp)(nil),      // 3: planetmsg.users.v1.TokenRsp
	(*User)(nil),          // 4: planetmsg.users.v1.User
	(*MsgRsp)(nil),        // 5: planetmsg.users.v1.MsgRsp
}
var file_planetmsg_users_v1_sign_up_service_proto_depIdxs = []int32{
	4, // 0: planetmsg.users.v1.SignUpService.AddUser:input_type -> planetmsg.users.v1.User
	0, // 1: planetmsg.users.v1.SignUpService.RequestValid:input_type -> planetmsg.users.v1.EmailReq
	1, // 2: planetmsg.users.v1.SignUpService.CheckValidCode:input_type -> planetmsg.users.v1.CheckEmailReq
	2, // 3: planetmsg.users.v1.SignUpService.Login:input_type -> planetmsg.users.v1.LoginReq
	5, // 4: planetmsg.users.v1.SignUpService.AddUser:output_type -> planetmsg.users.v1.MsgRsp
	5, // 5: planetmsg.users.v1.SignUpService.RequestValid:output_type -> planetmsg.users.v1.MsgRsp
	5, // 6: planetmsg.users.v1.SignUpService.CheckValidCode:output_type -> planetmsg.users.v1.MsgRsp
	3, // 7: planetmsg.users.v1.SignUpService.Login:output_type -> planetmsg.users.v1.TokenRsp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_planetmsg_users_v1_sign_up_service_proto_init() }
func file_planetmsg_users_v1_sign_up_service_proto_init() {
	if File_planetmsg_users_v1_sign_up_service_proto != nil {
		return
	}
	file_planetmsg_users_v1_base_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_planetmsg_users_v1_sign_up_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_planetmsg_users_v1_sign_up_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckEmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_planetmsg_users_v1_sign_up_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_planetmsg_users_v1_sign_up_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_planetmsg_users_v1_sign_up_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_planetmsg_users_v1_sign_up_service_proto_goTypes,
		DependencyIndexes: file_planetmsg_users_v1_sign_up_service_proto_depIdxs,
		MessageInfos:      file_planetmsg_users_v1_sign_up_service_proto_msgTypes,
	}.Build()
	File_planetmsg_users_v1_sign_up_service_proto = out.File
	file_planetmsg_users_v1_sign_up_service_proto_rawDesc = nil
	file_planetmsg_users_v1_sign_up_service_proto_goTypes = nil
	file_planetmsg_users_v1_sign_up_service_proto_depIdxs = nil
}
