// source: planetmsg/users/v1/user_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var planetmsg_users_v1_base_pb = require('../../../planetmsg/users/v1/base_pb.js');
goog.object.extend(proto, planetmsg_users_v1_base_pb);
goog.exportSymbol('proto.planetmsg.users.v1.IdReq', null, global);
goog.exportSymbol('proto.planetmsg.users.v1.UpdateSingleReq', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.planetmsg.users.v1.IdReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.planetmsg.users.v1.IdReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.planetmsg.users.v1.IdReq.displayName = 'proto.planetmsg.users.v1.IdReq';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.planetmsg.users.v1.UpdateSingleReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.planetmsg.users.v1.UpdateSingleReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.planetmsg.users.v1.UpdateSingleReq.displayName = 'proto.planetmsg.users.v1.UpdateSingleReq';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.planetmsg.users.v1.IdReq.prototype.toObject = function(opt_includeInstance) {
  return proto.planetmsg.users.v1.IdReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.planetmsg.users.v1.IdReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.planetmsg.users.v1.IdReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    userid: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.planetmsg.users.v1.IdReq}
 */
proto.planetmsg.users.v1.IdReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.planetmsg.users.v1.IdReq;
  return proto.planetmsg.users.v1.IdReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.planetmsg.users.v1.IdReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.planetmsg.users.v1.IdReq}
 */
proto.planetmsg.users.v1.IdReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setUserid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.planetmsg.users.v1.IdReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.planetmsg.users.v1.IdReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.planetmsg.users.v1.IdReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.planetmsg.users.v1.IdReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUserid();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 userId = 1;
 * @return {number}
 */
proto.planetmsg.users.v1.IdReq.prototype.getUserid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.planetmsg.users.v1.IdReq} returns this
 */
proto.planetmsg.users.v1.IdReq.prototype.setUserid = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.planetmsg.users.v1.UpdateSingleReq.prototype.toObject = function(opt_includeInstance) {
  return proto.planetmsg.users.v1.UpdateSingleReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.planetmsg.users.v1.UpdateSingleReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.planetmsg.users.v1.UpdateSingleReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    updatekey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    user: (f = msg.getUser()) && planetmsg_users_v1_base_pb.User.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.planetmsg.users.v1.UpdateSingleReq}
 */
proto.planetmsg.users.v1.UpdateSingleReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.planetmsg.users.v1.UpdateSingleReq;
  return proto.planetmsg.users.v1.UpdateSingleReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.planetmsg.users.v1.UpdateSingleReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.planetmsg.users.v1.UpdateSingleReq}
 */
proto.planetmsg.users.v1.UpdateSingleReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatekey(value);
      break;
    case 2:
      var value = new planetmsg_users_v1_base_pb.User;
      reader.readMessage(value,planetmsg_users_v1_base_pb.User.deserializeBinaryFromReader);
      msg.setUser(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.planetmsg.users.v1.UpdateSingleReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.planetmsg.users.v1.UpdateSingleReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.planetmsg.users.v1.UpdateSingleReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.planetmsg.users.v1.UpdateSingleReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUpdatekey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUser();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      planetmsg_users_v1_base_pb.User.serializeBinaryToWriter
    );
  }
};


/**
 * optional string updateKey = 1;
 * @return {string}
 */
proto.planetmsg.users.v1.UpdateSingleReq.prototype.getUpdatekey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.planetmsg.users.v1.UpdateSingleReq} returns this
 */
proto.planetmsg.users.v1.UpdateSingleReq.prototype.setUpdatekey = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional User user = 2;
 * @return {?proto.planetmsg.users.v1.User}
 */
proto.planetmsg.users.v1.UpdateSingleReq.prototype.getUser = function() {
  return /** @type{?proto.planetmsg.users.v1.User} */ (
    jspb.Message.getWrapperField(this, planetmsg_users_v1_base_pb.User, 2));
};


/**
 * @param {?proto.planetmsg.users.v1.User|undefined} value
 * @return {!proto.planetmsg.users.v1.UpdateSingleReq} returns this
*/
proto.planetmsg.users.v1.UpdateSingleReq.prototype.setUser = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.planetmsg.users.v1.UpdateSingleReq} returns this
 */
proto.planetmsg.users.v1.UpdateSingleReq.prototype.clearUser = function() {
  return this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.planetmsg.users.v1.UpdateSingleReq.prototype.hasUser = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.planetmsg.users.v1);
