// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: planetmsg/signUp/sign_up_service.proto

package signUpService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Account  string `protobuf:"bytes,2,opt,name=Account,proto3" json:"Account,omitempty"`
	NickName string `protobuf:"bytes,3,opt,name=NickName,proto3" json:"NickName,omitempty"`
	Pwd      string `protobuf:"bytes,4,opt,name=Pwd,proto3" json:"Pwd,omitempty"`
	Email    string `protobuf:"bytes,5,opt,name=Email,proto3" json:"Email,omitempty"`
	Phone    string `protobuf:"bytes,6,opt,name=Phone,proto3" json:"Phone,omitempty"`
	PicUrl   string `protobuf:"bytes,7,opt,name=PicUrl,proto3" json:"PicUrl,omitempty"`
	// google.protobuf.Timestamp BirthDay = 8;
	// google.protobuf.Timestamp CreateTime = 9;
	BirthDay   int64 `protobuf:"varint,8,opt,name=BirthDay,proto3" json:"BirthDay,omitempty"`
	CreateTime int64 `protobuf:"varint,9,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	Status     int32 `protobuf:"varint,10,opt,name=Status,proto3" json:"Status,omitempty"`
	// google.protobuf.Timestamp LastLoginTime = 11;
	LastLoginTime int64 `protobuf:"varint,11,opt,name=LastLoginTime,proto3" json:"LastLoginTime,omitempty"`
}

func (x *User) Reset() {
	*x = User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_planetmsg_signUp_sign_up_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *User) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *User) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetPicUrl() string {
	if x != nil {
		return x.PicUrl
	}
	return ""
}

func (x *User) GetBirthDay() int64 {
	if x != nil {
		return x.BirthDay
	}
	return 0
}

func (x *User) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetLastLoginTime() int64 {
	if x != nil {
		return x.LastLoginTime
	}
	return 0
}

type MsgRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *MsgRsp) Reset() {
	*x = MsgRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgRsp) ProtoMessage() {}

func (x *MsgRsp) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgRsp.ProtoReflect.Descriptor instead.
func (*MsgRsp) Descriptor() ([]byte, []int) {
	return file_planetmsg_signUp_sign_up_service_proto_rawDescGZIP(), []int{1}
}

func (x *MsgRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type EmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *EmailReq) Reset() {
	*x = EmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailReq) ProtoMessage() {}

func (x *EmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailReq.ProtoReflect.Descriptor instead.
func (*EmailReq) Descriptor() ([]byte, []int) {
	return file_planetmsg_signUp_sign_up_service_proto_rawDescGZIP(), []int{2}
}

func (x *EmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CheckEmailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email     string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	VaildCode string `protobuf:"bytes,2,opt,name=vaildCode,proto3" json:"vaildCode,omitempty"`
}

func (x *CheckEmailReq) Reset() {
	*x = CheckEmailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckEmailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckEmailReq) ProtoMessage() {}

func (x *CheckEmailReq) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckEmailReq.ProtoReflect.Descriptor instead.
func (*CheckEmailReq) Descriptor() ([]byte, []int) {
	return file_planetmsg_signUp_sign_up_service_proto_rawDescGZIP(), []int{3}
}

func (x *CheckEmailReq) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CheckEmailReq) GetVaildCode() string {
	if x != nil {
		return x.VaildCode
	}
	return ""
}

type LoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LoginName string `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Pwd       string `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
}

func (x *LoginReq) Reset() {
	*x = LoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginReq) ProtoMessage() {}

func (x *LoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginReq.ProtoReflect.Descriptor instead.
func (*LoginReq) Descriptor() ([]byte, []int) {
	return file_planetmsg_signUp_sign_up_service_proto_rawDescGZIP(), []int{4}
}

func (x *LoginReq) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *LoginReq) GetPwd() string {
	if x != nil {
		return x.Pwd
	}
	return ""
}

type TokenRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Atoken string `protobuf:"bytes,1,opt,name=Atoken,proto3" json:"Atoken,omitempty"`
	Rtoken string `protobuf:"bytes,2,opt,name=Rtoken,proto3" json:"Rtoken,omitempty"`
	Msg    string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *TokenRsp) Reset() {
	*x = TokenRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRsp) ProtoMessage() {}

func (x *TokenRsp) ProtoReflect() protoreflect.Message {
	mi := &file_planetmsg_signUp_sign_up_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRsp.ProtoReflect.Descriptor instead.
func (*TokenRsp) Descriptor() ([]byte, []int) {
	return file_planetmsg_signUp_sign_up_service_proto_rawDescGZIP(), []int{5}
}

func (x *TokenRsp) GetAtoken() string {
	if x != nil {
		return x.Atoken
	}
	return ""
}

func (x *TokenRsp) GetRtoken() string {
	if x != nil {
		return x.Rtoken
	}
	return ""
}

func (x *TokenRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_planetmsg_signUp_sign_up_service_proto protoreflect.FileDescriptor

var file_planetmsg_signUp_sign_up_service_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d, 0x73, 0x67, 0x2f, 0x73, 0x69, 0x67, 0x6e,
	0x55, 0x70, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x75, 0x70, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70,
	0x49, 0x64, 0x6c, 0x22, 0x9c, 0x02, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x77, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x50, 0x77, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x50, 0x68,
	0x6f, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x50, 0x69, 0x63, 0x55, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x69, 0x72, 0x74,
	0x68, 0x44, 0x61, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x42, 0x69, 0x72, 0x74,
	0x68, 0x44, 0x61, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x24, 0x0a, 0x0d,
	0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0d, 0x4c, 0x61, 0x73, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x1a, 0x0a, 0x06, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x20,
	0x0a, 0x08, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d,
	0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x22, 0x43, 0x0a, 0x0d, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x76, 0x61, 0x69, 0x6c, 0x64,
	0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x76, 0x61, 0x69, 0x6c,
	0x64, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x3a, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x70, 0x77, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x70, 0x77,
	0x64, 0x22, 0x4c, 0x0a, 0x08, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a,
	0x06, 0x41, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x52, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x52, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32,
	0xf0, 0x01, 0x0a, 0x0d, 0x53, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x2f, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0f, 0x2e, 0x73,
	0x69, 0x67, 0x6e, 0x55, 0x70, 0x49, 0x64, 0x6c, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x11, 0x2e,
	0x73, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x49, 0x64, 0x6c, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70,
	0x22, 0x00, 0x12, 0x38, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x12, 0x13, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x49, 0x64, 0x6c, 0x2e, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70,
	0x49, 0x64, 0x6c, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0e,
	0x43, 0x68, 0x65, 0x63, 0x6b, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x18,
	0x2e, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x49, 0x64, 0x6c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x55,
	0x70, 0x49, 0x64, 0x6c, 0x2e, 0x4d, 0x73, 0x67, 0x52, 0x73, 0x70, 0x22, 0x00, 0x12, 0x33, 0x0a,
	0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x13, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x49,
	0x64, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x73, 0x69,
	0x67, 0x6e, 0x55, 0x70, 0x49, 0x64, 0x6c, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x73, 0x70,
	0x22, 0x00, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x50, 0x6c, 0x75, 0x73, 0x48, 0x75, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x6d,
	0x73, 0x67, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70, 0x2f, 0x73, 0x69, 0x67, 0x6e, 0x55, 0x70,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_planetmsg_signUp_sign_up_service_proto_rawDescOnce sync.Once
	file_planetmsg_signUp_sign_up_service_proto_rawDescData = file_planetmsg_signUp_sign_up_service_proto_rawDesc
)

func file_planetmsg_signUp_sign_up_service_proto_rawDescGZIP() []byte {
	file_planetmsg_signUp_sign_up_service_proto_rawDescOnce.Do(func() {
		file_planetmsg_signUp_sign_up_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_planetmsg_signUp_sign_up_service_proto_rawDescData)
	})
	return file_planetmsg_signUp_sign_up_service_proto_rawDescData
}

var file_planetmsg_signUp_sign_up_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_planetmsg_signUp_sign_up_service_proto_goTypes = []interface{}{
	(*User)(nil),          // 0: signUpIdl.User
	(*MsgRsp)(nil),        // 1: signUpIdl.MsgRsp
	(*EmailReq)(nil),      // 2: signUpIdl.EmailReq
	(*CheckEmailReq)(nil), // 3: signUpIdl.CheckEmailReq
	(*LoginReq)(nil),      // 4: signUpIdl.LoginReq
	(*TokenRsp)(nil),      // 5: signUpIdl.TokenRsp
}
var file_planetmsg_signUp_sign_up_service_proto_depIdxs = []int32{
	0, // 0: signUpIdl.SignUpService.AddUser:input_type -> signUpIdl.User
	2, // 1: signUpIdl.SignUpService.RequestValid:input_type -> signUpIdl.EmailReq
	3, // 2: signUpIdl.SignUpService.CheckValidCode:input_type -> signUpIdl.CheckEmailReq
	4, // 3: signUpIdl.SignUpService.Login:input_type -> signUpIdl.LoginReq
	1, // 4: signUpIdl.SignUpService.AddUser:output_type -> signUpIdl.MsgRsp
	1, // 5: signUpIdl.SignUpService.RequestValid:output_type -> signUpIdl.MsgRsp
	1, // 6: signUpIdl.SignUpService.CheckValidCode:output_type -> signUpIdl.MsgRsp
	5, // 7: signUpIdl.SignUpService.Login:output_type -> signUpIdl.TokenRsp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_planetmsg_signUp_sign_up_service_proto_init() }
func file_planetmsg_signUp_sign_up_service_proto_init() {
	if File_planetmsg_signUp_sign_up_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_planetmsg_signUp_sign_up_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_planetmsg_signUp_sign_up_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_planetmsg_signUp_sign_up_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_planetmsg_signUp_sign_up_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckEmailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_planetmsg_signUp_sign_up_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_planetmsg_signUp_sign_up_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_planetmsg_signUp_sign_up_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_planetmsg_signUp_sign_up_service_proto_goTypes,
		DependencyIndexes: file_planetmsg_signUp_sign_up_service_proto_depIdxs,
		MessageInfos:      file_planetmsg_signUp_sign_up_service_proto_msgTypes,
	}.Build()
	File_planetmsg_signUp_sign_up_service_proto = out.File
	file_planetmsg_signUp_sign_up_service_proto_rawDesc = nil
	file_planetmsg_signUp_sign_up_service_proto_goTypes = nil
	file_planetmsg_signUp_sign_up_service_proto_depIdxs = nil
}
