name: build-protos

on:
  push:
    branches: ["main"]
  
permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.2
      
      - name: Setup Dart environment
        uses: dart-lang/setup-dart@v1.4
      
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      
      - name: Setup Protoc Plugins
        run: make install-plugins
      
      - name: Setup bufbuild
        uses: bufbuild/buf-setup-action@v1.27.2
      
      - name: Build
        run: make generate
      
      - name: refresh code
        run: |
          git config --global user.email "1050109853@qq.com"
          git config --global user.name "kid"
          git add .
          git commit -m "Generate code [skip ci]"
          git push origin main
        env:
          GITHUB_TOKEN: ${{secrets.KID_GIT_TOKEN}}
  release-please:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          command: manifest
        - name: Generate Release Artifact
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          



      