name: build-protos

on:
  push:
    branches: ["main"]
  
permissions: 
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v4.1.0
        with:
          go-version: 1.21
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.2
      
      - name: Setup Dart environment
        uses: dart-lang/setup-dart@v1.4
      
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      
      - name: Setup Protoc Plugins
        run: make install-plugins
      
      - name: Setup bufbuild
        uses: bufbuild/buf-setup-action@v1.27.2
      
      - name: Build
        run: make generate
      
      - name: Refresh Code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: apply auto code generation'
  release-please:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release-please
        with:
          command: manifest
          



      